// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SpectacolDbContext))]
    [Migration("20220104200508_Test2")]
    partial class Test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NrLocuri")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sali");
                });

            modelBuilder.Entity("Model.Spectacol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataSpectacol")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocuriVandute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PretBilet")
                        .HasColumnType("int");

                    b.Property<int?>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Spectacols");
                });

            modelBuilder.Entity("Model.Vanzare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LocuriVandute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrBileteVandute")
                        .HasColumnType("int");

                    b.Property<int?>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("SpectacolId")
                        .HasColumnType("int");

                    b.Property<int>("Suma")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.HasIndex("SpectacolId");

                    b.ToTable("Vanzari");
                });

            modelBuilder.Entity("Model.Spectacol", b =>
                {
                    b.HasOne("Model.Sala", null)
                        .WithMany("Spectacole")
                        .HasForeignKey("SalaId");
                });

            modelBuilder.Entity("Model.Vanzare", b =>
                {
                    b.HasOne("Model.Sala", null)
                        .WithMany("Vanzari")
                        .HasForeignKey("SalaId");

                    b.HasOne("Model.Spectacol", "Spectacol")
                        .WithMany()
                        .HasForeignKey("SpectacolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spectacol");
                });

            modelBuilder.Entity("Model.Sala", b =>
                {
                    b.Navigation("Spectacole");

                    b.Navigation("Vanzari");
                });
#pragma warning restore 612, 618
        }
    }
}
